### ISSUE TITLE
Not installable with modern Python

### ISSUE THREAD

**Issue by mwtoews** [inspirehep/jsonschema2rst#14]
This package does not seem to install in a modern Python environment. For instance, in a venv for Python 3.8 on Linux:
```
$ pip install jsonschema2rst
Collecting jsonschema2rst
  Downloading jsonschema2rst-0.1.4.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [97 lines of output]
      /tmp/py38/lib/python3.8/site-packages/setuptools_scm/integration.py:28: RuntimeWarning:
      ERROR: setuptools==44.0.0 is used in combination with setuptools_scm>=6.x
      
      Your build configuration is incomplete and previously worked by accident!
      setuptools_scm requires setuptools>=45
      
      
      This happens as setuptools is unable to replace itself when a activated build dependency
      requires a more recent setuptools version
      (it does not respect "setuptools>X" in setup_requires).
      
      
      setuptools>=31 is required for setup.cfg metadata support
      setuptools>=42 is required for pyproject.toml configuration support
      
      Suggested workarounds if applicable:
       - preinstalling build dependencies like setuptools_scm before running setup.py
       - installing setuptools_scm using the system package manager to ensure consistency
       - migrating from the deprecated setup_requires mechanism to pep517/518
         and using a pyproject.toml to declare build dependencies
         which are reliably pre-installed before running the build tools
      
        warnings.warn(
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [32 lines of output]
            /tmp/py38/lib/python3.8/site-packages/setuptools_scm/integration.py:28: RuntimeWarning:
            ERROR: setuptools==44.0.0 is used in combination with setuptools_scm>=6.x
      
            Your build configuration is incomplete and previously worked by accident!
            setuptools_scm requires setuptools>=45
      
      
            This happens as setuptools is unable to replace itself when a activated build dependency
            requires a more recent setuptools version
            (it does not respect "setuptools>X" in setup_requires).
      
      
            setuptools>=31 is required for setup.cfg metadata support
            setuptools>=42 is required for pyproject.toml configuration support
      
            Suggested workarounds if applicable:
             - preinstalling build dependencies like setuptools_scm before running setup.py
             - installing setuptools_scm using the system package manager to ensure consistency
             - migrating from the deprecated setup_requires mechanism to pep517/518
               and using a pyproject.toml to declare build dependencies
               which are reliably pre-installed before running the build tools
      
              warnings.warn(
            /tmp/py38/lib/python3.8/site-packages/setuptools/dist.py:473: UserWarning: Normalizing '0.5.5
            ' to '0.5.5'
              warnings.warn(
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help
      
            error: invalid command 'bdist_wheel'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for autosemver
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/tmp/py38/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/tmp/py38/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpzojvl85j', '--quiet', 'autosemver==0.5.5']' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-nlfl6lni/jsonschema2rst_00e53058fec24dd3a23f151eaf5bb989/setup.py", line 54, in <module>
          setup(
        File "/tmp/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
          _install_setup_requires(attrs)
        File "/tmp/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/tmp/py38/lib/python3.8/site-packages/setuptools/dist.py", line 718, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/tmp/py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
          dist = best[req.key] = env.best_match(
        File "/tmp/py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
          return self.obtain(req, installer)
        File "/tmp/py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
          return installer(requirement)
        File "/tmp/py38/lib/python3.8/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/tmp/py38/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
          raise DistutilsError(str(e))
      distutils.errors.DistutilsError: Command '['/tmp/py38/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpzojvl85j', '--quiet', 'autosemver==0.5.5']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by michamos** [comment]
Is this still an issue with the latest version?

**Comment by ioannistsanaktsidis** [comment]
Closing as this should now be the case anymore
